server.servlet.context-path=/api
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/authdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true

spring.application.name=lostandfound

# SMTP Configuration
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=true

# Google OAuth
google.client.id=${GOOGLE_CLIENT_ID:638378399138-2v3h9egmrh83vpqvq1q0l0c07u7k7m4v.apps.googleusercontent.com}

app.jwt.secret=${JWT_SECRET:SirFred123NganoDiayMongTananXxXG1CitUTopsAgain}
app.jwt.expirationInMs=${JWT_EXPIRATION_MS:86400000}

stripe.api.key=${STRIPE_API_KEY:}
payment.amount=${PAYMENT_AMOUNT:5000}
payment.currency=${PAYMENT_CURRENCY:php}

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

debug=true
